export const stateAnalytics = {
  "Andaman and Nicobar Islands": { mostGrownCrop: "Coconut", farmersUsingApp: 120, waterEfficiency: "80%", alerts: 15 },
  "Andhra Pradesh": { mostGrownCrop: "Rice", farmersUsingApp: 24500, waterEfficiency: "85%", alerts: 4120 },
  "Arunachal Pradesh": { mostGrownCrop: "Maize", farmersUsingApp: 850, waterEfficiency: "76%", alerts: 98 },
  "Assam": { mostGrownCrop: "Tea", farmersUsingApp: 12400, waterEfficiency: "90%", alerts: 2150 },
  "Bihar": { mostGrownCrop: "Wheat", farmersUsingApp: 18000, waterEfficiency: "78%", alerts: 3100 },
  "Chandigarh": { mostGrownCrop: "Wheat", farmersUsingApp: 45, waterEfficiency: "92%", alerts: 5 },
  "Chhattisgarh": { mostGrownCrop: "Rice", farmersUsingApp: 11200, waterEfficiency: "82%", alerts: 1980 },
  "Dadra and Nagar Haveli": { mostGrownCrop: "Paddy", farmersUsingApp: 150, waterEfficiency: "75%", alerts: 12 },
  "Daman and Diu": { mostGrownCrop: "Bajra", farmersUsingApp: 80, waterEfficiency: "70%", alerts: 8 },
  "Delhi": { mostGrownCrop: "Vegetables", farmersUsingApp: 500, waterEfficiency: "88%", alerts: 45 },
  "Goa": { mostGrownCrop: "Cashew", farmersUsingApp: 3200, waterEfficiency: "86%", alerts: 310 },
  "Gujarat": { mostGrownCrop: "Cotton", farmersUsingApp: 29500, waterEfficiency: "81%", alerts: 4800 },
  "Haryana": { mostGrownCrop: "Wheat", farmersUsingApp: 22400, waterEfficiency: "84%", alerts: 3950 },
  "Himachal Pradesh": { mostGrownCrop: "Apple", farmersUsingApp: 8600, waterEfficiency: "89%", alerts: 1050 },
  "Jammu and Kashmir": { mostGrownCrop: "Saffron", farmersUsingApp: 4500, waterEfficiency: "85%", alerts: 760 },
  "Jharkhand": { mostGrownCrop: "Rice", farmersUsingApp: 9800, waterEfficiency: "79%", alerts: 1450 },
  "Karnataka": { mostGrownCrop: "Coffee", farmersUsingApp: 31000, waterEfficiency: "87%", alerts: 5200 },
  "Kerala": { mostGrownCrop: "Rubber", farmersUsingApp: 15600, waterEfficiency: "92%", alerts: 2200 },
  "Ladakh": { mostGrownCrop: "Barley", farmersUsingApp: 350, waterEfficiency: "88%", alerts: 45 },
  "Lakshadweep": { mostGrownCrop: "Coconut", farmersUsingApp: 60, waterEfficiency: "95%", alerts: 2 },
  "Madhya Pradesh": { mostGrownCrop: "Soyabean", farmersUsingApp: 27800, waterEfficiency: "82%", alerts: 4600 },
  "Maharashtra": { mostGrownCrop: "Sugarcane", farmersUsingApp: 35400, waterEfficiency: "83%", alerts: 6100 },
  "Manipur": { mostGrownCrop: "Rice", farmersUsingApp: 1200, waterEfficiency: "80%", alerts: 140 },
  "Meghalaya": { mostGrownCrop: "Potato", farmersUsingApp: 1500, waterEfficiency: "81%", alerts: 180 },
  "Mizoram": { mostGrownCrop: "Bamboo", farmersUsingApp: 900, waterEfficiency: "78%", alerts: 110 },
  "Nagaland": { mostGrownCrop: "Maize", farmersUsingApp: 1100, waterEfficiency: "79%", alerts: 125 },
  "Odisha": { mostGrownCrop: "Rice", farmersUsingApp: 16400, waterEfficiency: "81%", alerts: 2700 },
  "Puducherry": { mostGrownCrop: "Paddy", farmersUsingApp: 400, waterEfficiency: "85%", alerts: 30 },
  "Punjab": { mostGrownCrop: "Wheat", farmersUsingApp: 26500, waterEfficiency: "88%", alerts: 4200 },
  "Rajasthan": { mostGrownCrop: "Mustard", farmersUsingApp: 21000, waterEfficiency: "75%", alerts: 3600 },
  "Sikkim": { mostGrownCrop: "Large Cardamom", farmersUsingApp: 2300, waterEfficiency: "94%", alerts: 210 },
  "Tamil Nadu": { mostGrownCrop: "Rice", farmersUsingApp: 28900, waterEfficiency: "86%", alerts: 4900 },
  "Telangana": { mostGrownCrop: "Cotton", farmersUsingApp: 18500, waterEfficiency: "84%", alerts: 3100 },
  "Tripura": { mostGrownCrop: "Rubber", farmersUsingApp: 1800, waterEfficiency: "82%", alerts: 240 },
  "Uttar Pradesh": { mostGrownCrop: "Sugarcane", farmersUsingApp: 32000, waterEfficiency: "80%", alerts: 5400 },
  "Uttarakhand": { mostGrownCrop: "Wheat", farmersUsingApp: 6700, waterEfficiency: "85%", alerts: 890 },
  "West Bengal": { mostGrownCrop: "Rice", farmersUsingApp: 24000, waterEfficiency: "83%", alerts: 3900 }
};

export const defaultStateAnalytics = {
  mostGrownCrop: "Mixed",
  farmersUsingApp: 0,
  waterEfficiency: "0%",
  alerts: 0
};
